In [16]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import numpy as np
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

In [14]:
bom_vectorizer = CountVectorizer()

bom_X = bom_vectorizer.fit_transform(corpus)
print("词汇：索引", bom_vectorizer.vocabulary_)
print("句子的向量：")
print(bom_X.toarray())#元素为每个词出现的次数

词汇：索引 {'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}
句子的向量：
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [18]:
tfidf_vectorizer = TfidfVectorizer()
#设置小数点的位数为2
np.set_printoptions(2)
tfidf_X = tfidf_vectorizer.fit_transform(corpus)
#词汇表
print(tfidf_vectorizer.vocabulary_)
print(tfidf_X.toarray())

{'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}
[[0.   0.47 0.58 0.38 0.   0.   0.38 0.   0.38]
 [0.   0.69 0.   0.28 0.   0.54 0.28 0.   0.28]
 [0.51 0.   0.   0.27 0.51 0.   0.27 0.51 0.27]
 [0.   0.47 0.58 0.38 0.   0.   0.38 0.   0.38]]


In [5]:
import gensim
import pprint
from gensim import corpora, models
from gensim.utils import simple_preprocess
doc_list = [
   "Hello, how are you?", 
   "How do you do?", 
   "Hey what are you doing? yes you What are you doing?"
]
doc_tokenized = [simple_preprocess(doc) for doc in doc_list]
dictionary = corpora.Dictionary()
BoW_corpus = [dictionary.doc2bow(doc, allow_update=True) for doc in doc_tokenized]
for doc in BoW_corpus:
   print([[dictionary[id], freq] for id, freq in doc])
import numpy as np
tfidf = models.TfidfModel(BoW_corpus, smartirs='ntc')
for doc in tfidf[BoW_corpus]:
   print([[dictionary[id], freq] for id, freq in doc])

[['are', 1], ['hello', 1], ['how', 1], ['you', 1]]
[['how', 1], ['you', 1], ['do', 2]]
[['are', 2], ['you', 3], ['doing', 2], ['hey', 1], ['what', 2], ['yes', 1]]
[['are', 0.40251125658964493], ['hello', 0.8050225131792899], ['how', 0.40251125658964493], ['you', 0.16705726536655124]]
[['how', 0.2413161129998105], ['you', 0.10015523607513224], ['do', 0.965264451999242]]
[['are', 0.29633595631969156], ['you', 0.1844858013859942], ['doing', 0.5926719126393831], ['hey', 0.29633595631969156], ['what', 0.5926719126393831], ['yes', 0.29633595631969156]]


In [12]:
from gensim.corpora.dictionary import Dictionary

doc_list = [
   "Hello, how are you?", 
   "How do you do?", 
   "Hey what are you doing? yes you What are you doing?"
]
doc_tokenized = [simple_preprocess(doc) for doc in doc_list]

dictionary = Dictionary(doc_tokenized)
num_docs = dictionary.num_docs
num_terms = len(dictionary.keys())
corpus_bow = [dictionary.doc2bow(doc) for doc in doc_tokenized]
from gensim.models.tfidfmodel import TfidfModel
tfidf = TfidfModel(corpus_bow)
corpus_tfidf = tfidf[corpus_bow]
from gensim.matutils import corpus2dense, corpus2csc
corpus_tfidf_dense = corpus2dense(corpus_tfidf, num_terms, num_docs)
corpus_tfidf_sparse = corpus2csc(corpus_tfidf, num_terms, num_docs)

TypeError: data type not understood

In [11]:
corpus_tfidf_dense

array([[0.3271846 , 0.        , 0.22731014],
       [0.8865103 , 0.        , 0.        ],
       [0.3271846 , 0.18147115, 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.9833963 , 0.        ],
       [0.        , 0.        , 0.6158994 ],
       [0.        , 0.        , 0.3079497 ],
       [0.        , 0.        , 0.6158994 ],
       [0.        , 0.        , 0.3079497 ]], dtype=float32)